"use client";

import { theme } from "@/theme";

const patients = [
  {
    id: 1,
    patient_id: "PAT001",
    patient_name: "Sharmila",
    gender: "Female",
    dob: "15/03/1995",
    age: "29",
    phone: "9876543210",
    email: "sharmila@email.com",
    address: "123 MG Road, Bangalore",
    blood_group: "O+",
    emergency_contact: "8765432109",
    insurance_details: "Star Health - Policy 987654",
    status: "Active",
  },
  {
    id: 2,
    patient_id: "PAT002",
    patient_name: "Rahul Verma",
    gender: "Male",
    dob: "22/08/1988",
    age: "36",
    phone: "9123456789",
    email: "rahul.v@email.com",
    address: "45 Residency Road, Mysore",
    blood_group: "B+",
    emergency_contact: "9988776655",
    insurance_details: "ICICI Lombard",
    status: "Active",
  },
  {
    id: 3,
    patient_id: "PAT003",
    patient_name: "Priya Nair",
    gender: "Female",
    dob: "10/11/2001",
    age: "23",
    phone: "9345678901",
    email: "priya.nair@email.com",
    address: "78 Brigade Road, Bangalore",
    blood_group: "A-",
    emergency_contact: "9876501234",
    insurance_details: "No Insurance",
    status: "Inactive",
  },
  {
    id: 4,
    patient_id: "PAT004",
    patient_name: "Monika",
    gender: "Female",
    dob: "05/07/2002",
    age: "24",
    phone: "9876500001",
    email: "monika@email.com",
    address: "Whitefield, Bangalore",
    blood_group: "O+",
    emergency_contact: "9876501001",
    insurance_details: "Star Health",
    status: "Active",
  },
  {
    id: 5,
    patient_id: "PAT005",
    patient_name: "Arun Kumar",
    gender: "Male",
    dob: "12/02/1990",
    age: "35",
    phone: "9876500002",
    email: "arun@email.com",
    address: "HSR Layout, Bangalore",
    blood_group: "A+",
    emergency_contact: "9876501002",
    insurance_details: "ICICI Lombard",
    status: "Active",
  },
  {
    id: 6,
    patient_id: "PAT006",
    patient_name: "Divya S",
    gender: "Female",
    dob: "25/04/1997",
    age: "28",
    phone: "9876500003",
    email: "divya@email.com",
    address: "Indiranagar, Bangalore",
    blood_group: "B+",
    emergency_contact: "9876501003",
    insurance_details: "HDFC Ergo",
    status: "Active",
  },
  {
    id: 7,
    patient_id: "PAT007",
    patient_name: "Karthik Raj",
    gender: "Male",
    dob: "18/09/1985",
    age: "40",
    phone: "9876500004",
    email: "karthik@email.com",
    address: "Electronic City, Bangalore",
    blood_group: "AB+",
    emergency_contact: "9876501004",
    insurance_details: "No Insurance",
    status: "Active",
  },
  {
    id: 8,
    patient_id: "PAT008",
    patient_name: "Sneha Reddy",
    gender: "Female",
    dob: "30/01/1993",
    age: "32",
    phone: "9876500005",
    email: "sneha@email.com",
    address: "Jayanagar, Bangalore",
    blood_group: "O-",
    emergency_contact: "9876501005",
    insurance_details: "Star Health",
    status: "Active",
  },
  {
    id: 9,
    patient_id: "PAT009",
    patient_name: "Ajay Kumar",
    gender: "Male",
    dob: "14/05/1987",
    age: "38",
    phone: "9876500006",
    email: "ajay@email.com",
    address: "BTM Layout, Bangalore",
    blood_group: "B-",
    emergency_contact: "9876501006",
    insurance_details: "Care Health",
    status: "Inactive",
  },
  {
    id: 10,
    patient_id: "PAT010",
    patient_name: "Lakshmi Devi",
    gender: "Female",
    dob: "21/12/1992",
    age: "33",
    phone: "9876500007",
    email: "lakshmi@email.com",
    address: "Rajajinagar, Bangalore",
    blood_group: "A+",
    emergency_contact: "9876501007",
    insurance_details: "Niva Bupa",
    status: "Active",
  },
  {
    id: 11,
    patient_id: "PAT011",
    patient_name: "Naveen Kumar",
    gender: "Male",
    dob: "11/06/1998",
    age: "27",
    phone: "9876500008",
    email: "naveen@email.com",
    address: "Marathahalli, Bangalore",
    blood_group: "O+",
    emergency_contact: "9876501008",
    insurance_details: "ICICI Lombard",
    status: "Active",
  },
  {
    id: 12,
    patient_id: "PAT012",
    patient_name: "Harini",
    gender: "Female",
    dob: "07/03/1999",
    age: "26",
    phone: "9876500009",
    email: "harini@email.com",
    address: "KR Puram, Bangalore",
    blood_group: "AB-",
    emergency_contact: "9876501009",
    insurance_details: "No Insurance",
    status: "Active",
  },
  {
    id: 13,
    patient_id: "PAT013",
    patient_name: "Suresh",
    gender: "Male",
    dob: "08/08/1984",
    age: "41",
    phone: "9876500010",
    email: "suresh@email.com",
    address: "Yelahanka, Bangalore",
    blood_group: "A-",
    emergency_contact: "9876501010",
    insurance_details: "Star Health",
    status: "Active",
  },
  {
    id: 14,
    patient_id: "PAT014",
    patient_name: "Rani",
    gender: "Female",
    dob: "09/09/1996",
    age: "29",
    phone: "9876500011",
    email: "rani@email.com",
    address: "Hebbal, Bangalore",
    blood_group: "B+",
    emergency_contact: "9876501011",
    insurance_details: "HDFC Ergo",
    status: "Active",
  },
  {
    id: 15,
    patient_id: "PAT015",
    patient_name: "Vikram",
    gender: "Male",
    dob: "17/10/1989",
    age: "36",
    phone: "9876500012",
    email: "vikram@email.com",
    address: "Banashankari, Bangalore",
    blood_group: "O+",
    emergency_contact: "9876501012",
    insurance_details: "Care Health",
    status: "Inactive",
  },
  {
    id: 16,
    patient_id: "PAT016",
    patient_name: "Keerthi",
    gender: "Female",
    dob: "03/01/2000",
    age: "25",
    phone: "9876500013",
    email: "keerthi@email.com",
    address: "Kengeri, Bangalore",
    blood_group: "AB+",
    emergency_contact: "9876501013",
    insurance_details: "No Insurance",
    status: "Active",
  },
  {
    id: 17,
    patient_id: "PAT017",
    patient_name: "Manoj",
    gender: "Male",
    dob: "20/04/1991",
    age: "34",
    phone: "9876500014",
    email: "manoj@email.com",
    address: "Malleshwaram, Bangalore",
    blood_group: "A+",
    emergency_contact: "9876501014",
    insurance_details: "Star Health",
    status: "Active",
  },
  {
    id: 18,
    patient_id: "PAT018",
    patient_name: "Pooja",
    gender: "Female",
    dob: "29/05/1994",
    age: "31",
    phone: "9876500015",
    email: "pooja@email.com",
    address: "JP Nagar, Bangalore",
    blood_group: "O-",
    emergency_contact: "9876501015",
    insurance_details: "ICICI Lombard",
    status: "Active",
  },
  {
    id: 19,
    patient_id: "PAT019",
    patient_name: "Deepak",
    gender: "Male",
    dob: "13/11/1986",
    age: "39",
    phone: "9876500016",
    email: "deepak@email.com",
    address: "Bellandur, Bangalore",
    blood_group: "B+",
    emergency_contact: "9876501016",
    insurance_details: "HDFC Ergo",
    status: "Active",
  },
  {
    id: 20,
    patient_id: "PAT020",
    patient_name: "Gayathri",
    gender: "Female",
    dob: "15/06/1998",
    age: "27",
    phone: "9876500017",
    email: "gayathri@email.com",
    address: "Sarjapur Road, Bangalore",
    blood_group: "A+",
    emergency_contact: "9876501017",
    insurance_details: "No Insurance",
    status: "Active",
  },
  {
    id: 21,
    patient_id: "PAT021",
    patient_name: "Rohit Sharma",
    gender: "Male",
    dob: "24/02/1993",
    age: "32",
    phone: "9876500018",
    email: "rohit@email.com",
    address: "Koramangala, Bangalore",
    blood_group: "O+",
    emergency_contact: "9876501018",
    insurance_details: "Care Health",
    status: "Active",
  },
  {
    id: 22,
    patient_id: "PAT022",
    patient_name: "Aishwarya",
    gender: "Female",
    dob: "11/12/1997",
    age: "28",
    phone: "9876500019",
    email: "aishwarya@email.com",
    address: "Hosur Road, Bangalore",
    blood_group: "AB+",
    emergency_contact: "9876501019",
    insurance_details: "Star Health",
    status: "Active",
  },
  {
    id: 23,
    patient_id: "PAT023",
    patient_name: "Bharath",
    gender: "Male",
    dob: "19/07/1988",
    age: "37",
    phone: "9876500020",
    email: "bharath@email.com",
    address: "Basavanagudi, Bangalore",
    blood_group: "B-",
    emergency_contact: "9876501020",
    insurance_details: "ICICI Lombard",
    status: "Inactive",
  },
  {
    id: 24,
    patient_id: "PAT024",
    patient_name: "Swathi",
    gender: "Female",
    dob: "08/10/1995",
    age: "30",
    phone: "9876500021",
    email: "swathi@email.com",
    address: "Ulsoor, Bangalore",
    blood_group: "O+",
    emergency_contact: "9876501021",
    insurance_details: "Niva Bupa",
    status: "Active",
  },
  {
    id: 25,
    patient_id: "PAT025",
    patient_name: "Kishore",
    gender: "Male",
    dob: "27/03/1987",
    age: "38",
    phone: "9876500022",
    email: "kishore@email.com",
    address: "RR Nagar, Bangalore",
    blood_group: "A-",
    emergency_contact: "9876501022",
    insurance_details: "No Insurance",
    status: "Active",
  },
  {
    id: 26,
    patient_id: "PAT026",
    patient_name: "Nisha",
    gender: "Female",
    dob: "04/04/2001",
    age: "24",
    phone: "9876500023",
    email: "nisha@email.com",
    address: "Vijayanagar, Bangalore",
    blood_group: "AB+",
    emergency_contact: "9876501023",
    insurance_details: "Star Health",
    status: "Active",
  },
  {
    id: 27,
    patient_id: "PAT027",
    patient_name: "Sanjay",
    gender: "Male",
    dob: "30/09/1990",
    age: "35",
    phone: "9876500024",
    email: "sanjay@email.com",
    address: "Peenya, Bangalore",
    blood_group: "O+",
    emergency_contact: "9876501024",
    insurance_details: "HDFC Ergo",
    status: "Active",
  },
  {
    id: 28,
    patient_id: "PAT028",
    patient_name: "Meena",
    gender: "Female",
    dob: "22/06/1992",
    age: "33",
    phone: "9876500025",
    email: "meena@email.com",
    address: "Chandapura, Bangalore",
    blood_group: "B+",
    emergency_contact: "9876501025",
    insurance_details: "Care Health",
    status: "Active",
  },
  {
    id: 29,
    patient_id: "PAT029",
    patient_name: "Arvind",
    gender: "Male",
    dob: "12/01/1985",
    age: "41",
    phone: "9876500026",
    email: "arvind@email.com",
    address: "Attibele, Bangalore",
    blood_group: "A+",
    emergency_contact: "9876501026",
    insurance_details: "Star Health",
    status: "Active",
  },
  {
    id: 30,
    patient_id: "PAT030",
    patient_name: "Lavanya",
    gender: "Female",
    dob: "14/08/1999",
    age: "26",
    phone: "9876500027",
    email: "lavanya@email.com",
    address: "Whitefield, Bangalore",
    blood_group: "O-",
    emergency_contact: "9876501027",
    insurance_details: "ICICI Lombard",
    status: "Active",
  },
];
export default function ContactList() {
  return (
    <div
      className="mt-6 border rounded-2xl overflow-hidden"
      style={{ borderColor: theme.border }}
    >
      {/* Horizontal Scroll Wrapper */}
      <div className="overflow-x-auto">
        <table className="w-full min-w-[1200px]">   {/* min-w ensures table doesn't shrink */}
          <thead
            style={{ background: theme.primaryLight }}
          >
            <tr>
              <th className="p-4 text-left whitespace-nowrap">Patient ID</th>
              <th className="p-4 text-left whitespace-nowrap">Name</th>
              <th className="p-4 text-left whitespace-nowrap">Gender</th>
              <th className="p-4 text-left whitespace-nowrap">DOB</th>
              <th className="p-4 text-left whitespace-nowrap">Age</th>
              <th className="p-4 text-left whitespace-nowrap">Phone</th>
              <th className="p-4 text-left whitespace-nowrap">Email</th>
              <th className="p-4 text-left whitespace-nowrap">Address</th>
              <th className="p-4 text-left whitespace-nowrap">Blood Group</th>
              <th className="p-4 text-left whitespace-nowrap">Emergency Contact</th>
              <th className="p-4 text-left whitespace-nowrap">Insurance Details</th>
              <th className="p-4 text-left whitespace-nowrap">Status</th>
            </tr>
          </thead>

          <tbody>
            {patients.map((patient) => (
              <tr key={patient.id} className="border-t hover:bg-gray-50">
                <td className="p-4 whitespace-nowrap">{patient.patient_id}</td>
                <td className="p-4 whitespace-nowrap">{patient.patient_name}</td>
                <td className="p-4 whitespace-nowrap">{patient.gender}</td>
                <td className="p-4 whitespace-nowrap">{patient.dob}</td>
                <td className="p-4 whitespace-nowrap">{patient.age}</td>
                <td className="p-4 whitespace-nowrap">{patient.phone}</td>
                <td className="p-4 whitespace-nowrap">{patient.email}</td>
                <td className="p-4 max-w-xs truncate">{patient.address}</td>
                <td className="p-4 whitespace-nowrap">{patient.blood_group}</td>
                <td className="p-4 whitespace-nowrap">{patient.emergency_contact}</td>
                <td className="p-4 max-w-xs truncate">{patient.insurance_details}</td>
                <td className="p-4 whitespace-nowrap">
                  <span className={`px-3 py-1 rounded-full text-xs font-medium ${
                    patient.status === "Active" 
                      ? "bg-green-100 text-green-700" 
                      : "bg-red-100 text-red-700"
                  }`}>
                    {patient.status}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}